ASG recordings and image summit minutes
uapi-group/docs pull request #33
Opened 2024-10-14 14:29 UTC by bluca

2024-10-14 14:37 UTC, behrmann commented on conferences/2024-09-25__All-Systems-Go.md
> +Please find the [full list of talks recordings on Youtube](https://www.youtube.com/playlist?list=PLWYdJViL9EipIImmvuoGFAeS-lKeHH2DD).
```suggestion
## Talk recordings
Please find the [full list of talk recordings on Youtube](https://www.youtube.com/playlist?list=PLWYdJViL9EipIImmvuoGFAeS-lKeHH2DD).
```

2024-10-14 14:39 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +    * Recent dm-verity support for /nix/store (incl. offline Secure Boot signing support)
```suggestion
    * Recent dm-verity support for `/nix/store` (incl. offline Secure Boot signing support)
```

2024-10-14 14:42 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * Comment: It’s hard to specify root= with UKI
```suggestion
  * Comment: It’s hard to specify `root=` with UKI
```

2024-10-14 14:42 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * /etc/os-release add new field, or re-purpose IMAGE\_ID
```suggestion
  * `/etc/os-release` add new field, or re-purpose `IMAGE_ID`
```

2024-10-14 14:42 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * Apt has global trusted.gpg.d directory, being phased out, specified inline in the src line
```suggestion
  * Apt has global `trusted.gpg.d` directory, being phased out, specified inline in the src line
```

2024-10-14 14:43 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * why not pkcs\#7
```suggestion
  * why not PKCS\#7
```

2024-10-14 14:43 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +    * Pkcs7 is x509 so that additional things can be added, like application-specific purpose extensions
```suggestion
    * PKCS\#7 is x509 so that additional things can be added, like application-specific purpose extensions
```

2024-10-14 14:43 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * Should support the usual /usr, /etc, /run priorities
```suggestion
  * Should support the usual `/usr`, `/etc`, `/run` priorities
```

2024-10-14 14:44 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * Reject AF\_UNIX sockets in /etc/ or /usr/
```suggestion
  * Reject `AF_UNIX` sockets in `/etc/` or `/usr/`
```

2024-10-14 14:45 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * TODO: file RFE on systemd to track list of policies
Anybody did that yet?

2024-10-14 14:45 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * Make program visible in BPF FS when loaded, so you can do ConditionPathExists=/sys/filesystem/bpf (TODO: fix this)
```suggestion
  * Make program visible in BPF FS when loaded, so you can do `ConditionPathExists=/sys/filesystem/bpf` (TODO: fix this)
```

2024-10-14 14:46 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +    * pidfd\_spawn, shadow/gshadow, printf string formatter, detected by pkgconfig
```suggestion
    * `pidfd_spawn`, shadow/gshadow, `printf` string formatter, detected by pkgconfig
```

2024-10-14 14:46 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * Persisting /etc/machine-id
```suggestion
  * Persisting `/etc/machine-id`
```

2024-10-14 14:48 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +    * MicroOS already mounts /var/ (and /etc/ overlay) in the initrd
```suggestion
  * Deriving the machine-id for `/var`, even though /var is probably storing the mutable `/etc` context
  * Handling presets. Store them in `/usr` somehow?
  * Possible solution: Just mount `/var` from initrd? (Who does this actually affect, and do they use image-based / confexts / whatever?)
  * Move mounts that exist on `/etc` when reapplying, writable `/etc` on top of the stack
  * Overlayfs works by using the superblock for each elements, pins it, and doesn’t look at the VFS at all, so it needs to be handled by the confext layer
  * How to handle cases where only `/var` should be persisted?
    * repart uses the ephemeral machine-id to create `/var`
    * there is now also `systemd.machine-id=firmware`
    * Could add a mechanism to persist machine-id via tpm (NV index, allows factory reset) or system credential
    * could also use the `/var` partition UUID as machine-id?
      * problematic from the security perspective, needs some authentication
  * perhaps reopen the discussion to mount `/var` early (in the initramfs)
    * MicroOS already mounts `/var` (and `/etc` overlay) in the initrd
```

2024-10-14 14:50 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +## Attendee's projects
```suggestion
## Attendee's projects
```

2024-10-14 14:53 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * IPA has existing systems with large amounts of mapping, want to make it configurable
```suggestion
  * FreeIPA has existing systems with large amounts of mapping, want to make it configurable
```

2024-10-14 14:54 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +* Hermetic /usr/ \+ Hermetic /etc/
```suggestion
* Hermetic /usr/ \+ Hermetic `/etc`
```

2024-10-14 14:54 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * /etc/shells is read by many things directly
```suggestion
    * related: `/etc/protocols`
  * `/etc/shells` is read by many things directly
```

2024-10-14 14:54 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * also relates to random top-level paths (mount points in /, container usecases, /opt)
```suggestion
  * also relates to random top-level paths (mount points in `/`, container usecases, `/opt`)
```

2024-10-14 14:55 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +    * \--lock=auto option like cryptenroll
```suggestion
    * `--lock=auto` option like cryptenroll
```

2024-10-14 14:55 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * Golden measurements supported, provided by vendor (in /usr), derive the rest from hardware
```suggestion
  * Golden measurements supported, provided by vendor (in `/usr`), derive the rest from hardware
```

2024-10-14 14:56 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * CHECK BERLIN MARATHON DATES
[September 21, 2025](https://www.bmw-berlin-marathon.com/en/)

2024-10-14 14:56 UTC, behrmann commented on minutes/2024-09-24__Image-based-linux-summit.md
> +* uki.d vs uki.vendor.d dropins for factory reset
```suggestion
* `uki.d` vs `uki.vendor.d` dropins for factory reset
```

2024-10-14 18:11 UTC, bluca commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * TODO: file RFE on systemd to track list of policies
haven't seen it yet

2024-10-14 22:09 UTC, alatiera commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * SSS support was being worked on, but keys are combined in software on the CPU, so the spooks can get at you
Is SSS a thing or was it meant to be SSH?

2024-10-16 09:23 UTC, mauromorales commented on minutes/2024-09-24__Image-based-linux-summit.md
> +* [PostmarketOS](https://postmarketos.org/)
Could we also add Kairos here? it's following the the Trusted Boot implementation defined by UAPI and systemd. I gave a presentation at the conference :) 

```suggestion
* [PostmarketOS](https://postmarketos.org/)
* [Kairos](https://kairos.io/)
```

2024-10-16 09:23 UTC, mauromorales commented on minutes/2024-09-24__Image-based-linux-summit.md
> +* [PostmarketOS](https://postmarketos.org/)
sorry I see this is for the summit, removing

2024-10-16 09:27 UTC, mauromorales commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * Try after ASG, if we can do ASG Tue/Wed
very nice options 👏

2024-10-16 09:36 UTC, mauromorales commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * New installer for GNOME OS, no longer supports /etc/fstab
```suggestion
  * New installer for GNOME OS, no longer supports `/etc/fstab`
```

2024-10-16 09:37 UTC, mauromorales commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * Reject `AF_UNIX` sockets in /etc/ or `/usr/`
```suggestion
  * Reject `AF_UNIX` sockets in `/etc/` or `/usr/`
```

2024-10-16 09:39 UTC, mauromorales commented on minutes/2024-09-24__Image-based-linux-summit.md
> +  * TODO: ask to get it published
Do any of these TODO's need to go to the action items at the bottom?

2024-10-16 09:43 UTC, mauromorales commented
@bluca nice write-up. The summary was particularly good for me since I just joined the group :) I'll share it with the rest of the Kairos team.

2024-10-16 12:32 UTC, keszybz requested changes

2024-10-16 12:32 UTC, keszybz commented on conferences/2024-09-25__All-Systems-Go.md
> +All Systems Go! is a conference focused on foundational user-space Linux technologies. Its goal is to provide a gathering place for both contributors and users of projects that make up the foundation
Semantic breaks please. No need to bunch this all up together.

2024-10-16 12:32 UTC, keszybz commented on conferences/2024-09-25__All-Systems-Go.md
> +The UAPI Group was well-represented with many speakers and related talks. Learn more at https://all-systems-go.io/
Here too. And final period is missing.

2024-10-16 14:37 UTC, merged